---
# If you need to download RHEL 9.x get a offline api key from here:  https://access.redhat.com/management/api
# Get the checksum for RHEL 9.x from the Red Hat Downloads page. 
# Then add the API Key & Checksum to roles/pxe/defaults/main.yml
# Then set DOWNLOAD_RHEL: to "true"

- hosts: pxe
  user: metal01
  become: true
  vars:
    DOWNLOAD_RHEL: false
  roles:
    - pxe
##########################
###      Ansible       ###
##########################
#  Add your public key to remote server's ./ssh/authorized_keys file
#  Then add your private key:
#
#    ssh-add ~/.ssh/id_rsa
#
#  Then run ansible -m ping to make sure it works
#
#    ansible -i inventory <Target_Host> -m ping
#
#     Dell_R750 | SUCCESS => {
#       "ansible_facts": {
#           "discovered_interpreter_python": "/usr/libexec/platform-python"
#     },
#     "changed": false,
#     "ping": "pong"
#     }
#
# ansible-playbook -i inventory main.yaml
